# Define un servicio llamado 'web-server-unicorn'
services:
 web-server-unicorn:
  # Configura el servicio para construir una imagen a partir de un Dockerfile
  build:
    # Define el contexto de la construcción, que es el conjunto de archivos que Docker puede acceder durante la construcción
    context: .
    # Especifica el Dockerfile que Docker debe usar para construir la imagen
    dockerfile: Dockerfile
  # Mapea el puerto 80 del contenedor al puerto 80 del host
  volumes:
    - .:/app
  ports:
    - '8080:80'
